
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcjchjxyrlenocqfagmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jamNoanh5cmxlbm9jcWZhZ21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTk1NjEsImV4cCI6MjA1ODEzNTU2MX0.A1Ow_mLynSphYuePUyGKTS8qkqem3jwewoW9eZ-9w4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
